[package]
name = "keysafe"
version = "0.1.0"
authors = ["rohitgurunath"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
crypto = { path = "./crypto" }
secret_box = { path = "./secret_box" }